version: '2'
services:
    tribos-app:
        image: tribos
        external_links:
            - tribos-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tribos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tribos-mysql:
        extends:
            file: mysql.yml
            service: tribos-mysql
